  
name: Pull Request CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests  
        run: mvn test

      - name: Run Checkstyle with Google Style
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.REVIEW_DOG_GITHUB_TOKEN }}
          reporter: github-check
          level: warning
          # Checkstyle configuration specifies which rule-set to apply during the scan.
          # There are 2 built-in configurations - 1) google_checks.xml 2) sun_checks.xml
          # Default is google_checks.xml and we don't need to specify checkstyle_config property in that case. 
          # https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml
          # To leverage sun_checks.xml, uncomment the following line of code.
          # checkstyle_config: sun_checks.xml
