  
name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests  
        run: mvn test
        
      # - name: Build and push Docker image  
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: myapp  
      #     tags: v1, latest
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
        
      # Add steps to deploy the application here    
